In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('IPL_Matches_Data_2008_2026.csv')

In [3]:
df.head()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_name       1243 non-null   object
 1   season           1243 non-null   object
 2   match_number     1169 non-null   float64
 3   date             1243 non-null   object
 4   city             1243 non-null   object
 5   venue            1243 non-null   object
 6   team1            1243 non-null   object
 7   team2            1243 non-null   object
 8   toss_winner      1243 non-null   object
 9   toss_decision    1243 non-null   object
 10  team1_runs       1243 non-null   int64
 11  team1_wickets    1243 non-null   int64
 12  team2_runs       1243 non-null   int64
 13  team2_wickets    1243 non-null   int64
 14  winner           1218 non-null   object
 15  result_type      1243 non-null   object
 16  win_by_runs      1243 non-null   int64
 17  win_by_wickets   1243 non-null   int64
 18  player_of_match  1234 non-null   object
 19  match_referee    1243 non-null   object
 20  umpire1          1243 non-null   object
 21  umpire2          1243 non-null   object
 22  tv_umpire        1243 non-null   object
 23  reserve_umpire   1243 non-null   object
 24  match_type       1243 non-null   object
 25  overs_limit      1243 non-null   int64
 26  balls_per_over   1243 non-null   int64
 27  gender           1243 non-null   object
 28  team_type        1243 non-null   object
 29  team1_players    1243 non-null   object
 30  team2_players    1243 non-null   object
dtypes: float64(1), int64(8), object(22)
memory usage: 301.2+ KB

In [5]:
df['date']=pd.to_datetime(df['date'],dayfirst=True)

In [6]:
df.date.dtype

dtype('<M8[ns]')

In [7]:
df.isna().sum()

event_name          0
season              0
match_number       74
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     9
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
match_type          0
overs_limit         0
balls_per_over      0
gender              0
team_type           0
team1_players       0
team2_players       0
dtype: int64

In [8]:
df.columns[df.isna().sum() >0]

Index(['match_number', 'winner', 'player_of_match'], dtype='object')

#### match_number Nan Handling

In [9]:
df[df['match_number'].isna()]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
55,Indian Premier League,2007/08,NaN,2008-05-30,Mumbai,Wankhede Stadium,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,field,...,RE Koertzen,BR Doctrove,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, TM D...","GC Smith, SA Asnodkar, Sohail Tanvir, SR Watso..."
56,Indian Premier League,2007/08,NaN,2008-05-31,Mumbai,Wankhede Stadium,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,bat,...,DJ Harper,K Hariharan,Unknown,T20,20,6,male,club,"PA Patel, S Vidyut, SK Raina, MS Dhoni, CK Kap...","SE Marsh, JR Hopes, KC Sangakkara, Yuvraj Sing..."
57,Indian Premier League,2007/08,NaN,2008-06-01,Mumbai,Dr DY Patil Sports Academy,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,...,RE Koertzen,DJ Harper,MR Singh,T20,20,6,male,club,"PA Patel, S Vidyut, SK Raina, JA Morkel, MS Dh...","NK Patel, SA Asnodkar, Kamran Akmal, SR Watson..."
112,Indian Premier League,2009,NaN,2009-05-22,Centurion,SuperSport Park,Delhi Daredevils,Deccan Chargers,Deccan Chargers,field,...,DJ Harper,RE Koertzen,JD Cloete,T20,20,6,male,club,"G Gambhir, DA Warner, V Sehwag, TM Dilshan, AB...","AC Gilchrist, HH Gibbs, AA Bilakhia, TL Suman,..."
113,Indian Premier League,2009,NaN,2009-05-23,Johannesburg,New Wanderers Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,field,...,SJA Taufel,IL Howell,KH Hurter,T20,20,6,male,club,"JH Kallis, MK Pandey, RE van der Merwe, R Drav...","PA Patel, ML Hayden, MS Dhoni, SK Raina, JA Mo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,Indian Premier League,2025,NaN,2025-06-03,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Punjab Kings,Punjab Kings,field,...,Nitin Menon,CB Gaffaney,KN Ananthapadmanabhan,T20,20,6,male,club,"Suyash Sharma, PD Salt, V Kohli, MA Agarwal, R...","YS Chahal, Priyansh Arya, P Simran Singh, JP I..."
1239,Indian Premier League,2026,NaN,2026-05-26,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,...,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,T20,20,6,male,club,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
1240,Indian Premier League,2026,NaN,2026-05-27,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,...,UV Gandhe,R Pandit,SJ Nogajski,T20,20,6,male,club,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
1241,Indian Premier League,2026,NaN,2026-05-29,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,...,SJ Nogajski,AT Holdstock,UV Gandhe,T20,20,6,male,club,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
1242,Indian Premier League,2026,NaN,2026-05-31,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,Nitin Menon,J Madanagopal,VK Sharma,T20,20,6,male,club,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."

In [10]:
# Here We can clearly see there's a pattern in the nan values


print(df['match_number'].iloc[53])  
print(df['match_number'].iloc[54])
print(df['match_number'].iloc[55])
print(df['match_number'].iloc[56])
print("\n")
print(df['match_number'].iloc[1237])
print(df['match_number'].iloc[1238])
print(df['match_number'].iloc[1239])
print(df['match_number'].iloc[1240])

55.0
56.0
nan
nan


69.0
70.0
nan
nan

In [11]:
for i in range(1, len(df)):
    if pd.isna(df.loc[i, "match_number"]):
        df.loc[i, "match_number"] = df.loc[i - 1, "match_number"] + 1

In [12]:
print(df['match_number'].iloc[53])  
print(df['match_number'].iloc[54])
print(df['match_number'].iloc[55])
print(df['match_number'].iloc[56])
print("\n")
print(df['match_number'].iloc[1237])
print(df['match_number'].iloc[1238])
print(df['match_number'].iloc[1239])
print(df['match_number'].iloc[1240])

55.0
56.0
57.0
58.0


69.0
70.0
71.0
72.0

#### winner Nan Handling

In [13]:
df.columns

Index(['event_name', 'season', 'match_number', 'date', 'city', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'team1_runs',
       'team1_wickets', 'team2_runs', 'team2_wickets', 'winner', 'result_type',
       'win_by_runs', 'win_by_wickets', 'player_of_match', 'match_referee',
       'umpire1', 'umpire2', 'tv_umpire', 'reserve_umpire', 'match_type',
       'overs_limit', 'balls_per_over', 'gender', 'team_type', 'team1_players',
       'team2_players'],
      dtype='object')

In [14]:
# Winner Column is nan when result type is tie or no result

df[df['winner'].isna()][['event_name', 'season', 'match_number', 'date', 'city', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'team1_runs',
       'team1_wickets', 'team2_runs', 'team2_wickets', 'winner', 'result_type',
       'win_by_runs', 'win_by_wickets','win_by_runs', 'win_by_wickets']]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,win_by_runs,win_by_wickets
66,Indian Premier League,2009,10.0,2009-04-23,Cape Town,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,165,9,168,6,NaN,tie,0,0,0,0
130,Indian Premier League,2009/10,16.0,2010-03-21,Chennai,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,145,9,146,9,NaN,tie,0,0,0,0
241,Indian Premier League,2011,68.0,2011-05-21,Delhi,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,56,3,0,0,NaN,no result,0,0,0,0
328,Indian Premier League,2013,7.0,2013-04-07,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,150,7,145,8,NaN,tie,0,0,0,0
342,Indian Premier League,2013,21.0,2013-04-16,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,167,7,163,7,NaN,tie,0,0,0,0
416,Indian Premier League,2014,19.0,2014-04-29,Abu Dhabi,Sheikh Zayed Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,163,10,163,5,NaN,tie,0,0,0,0
475,Indian Premier League,2015,18.0,2015-04-21,Ahmedabad,"Sardar Patel Stadium, Motera",Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,197,8,206,8,NaN,tie,0,0,0,0
485,Indian Premier League,2015,29.0,2015-04-29,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,200,7,0,0,NaN,no result,0,0,0,0
511,Indian Premier League,2015,55.0,2015-05-17,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,2,0,187,5,NaN,no result,0,0,0,0
610,Indian Premier League,2017,35.0,2017-04-29,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,159,9,164,12,NaN,tie,0,0,0,0
705,Indian Premier League,2019,10.0,2019-03-30,Delhi,Arun Jaitley Stadium,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,192,9,195,7,NaN,tie,0,0,0,0
744,Indian Premier League,2019,49.0,2019-04-30,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,62,7,41,1,NaN,no result,0,0,0,0
746,Indian Premier League,2019,51.0,2019-05-02,Mumbai,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,171,5,170,8,NaN,tie,0,0,0,0
757,Indian Premier League,2020/21,2.0,2020-09-20,Unknown,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,160,8,159,10,NaN,tie,0,0,0,0
765,Indian Premier League,2020/21,10.0,2020-09-28,Unknown,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,212,3,208,6,NaN,tie,0,0,0,0
790,Indian Premier League,2020/21,35.0,2020-10-18,Abu Dhabi,Sheikh Zayed Stadium,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,166,5,165,8,NaN,tie,0,0,0,0
791,Indian Premier League,2020/21,36.0,2020-10-18,Unknown,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,192,8,196,8,NaN,tie,0,0,0,0
835,Indian Premier League,2021,20.0,2021-04-25,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,167,4,166,7,NaN,tie,0,0,0,0
994,Indian Premier League,2023,45.0,2023-05-03,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,125,7,0,0,NaN,no result,0,0,0,0
1126,Indian Premier League,2025,32.0,2025-04-16,Delhi,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,201,5,199,7,NaN,tie,0,0,0,0
1138,Indian Premier League,2025,44.0,2025-04-26,Kolkata,"Eden Gardens, Kolkata",Punjab Kings,Kolkata Knight Riders,Punjab Kings,bat,201,4,7,0,NaN,no result,0,0,0,0
1149,Indian Premier League,2025,55.0,2025-05-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Delhi Capitals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,133,7,0,0,NaN,no result,0,0,0,0
1152,Indian Premier League,2025,58.0,2025-05-08,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Punjab Kings,Delhi Capitals,Punjab Kings,bat,122,1,0,0,NaN,no result,0,0,0,0
1180,Indian Premier League,2026,12.0,2026-04-06,Kolkata,"Eden Gardens, Kolkata",Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,bat,25,2,0,0,NaN,no result,0,0,0,0
1206,Indian Premier League,2026,38.0,2026-04-26,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Kolkata Knight Riders,Lucknow Super Giants,Lucknow Super Giants,field,159,7,156,10,NaN,tie,0,0,0,0

In [15]:
df['winner'] = df['winner'].fillna(df['result_type'].map({'tie': 'Tie', 'no result': 'No Result'}))

In [16]:
print(df['winner'].isna().sum())

0

#### player_of_match Nan Handling

In [17]:
# Here player_of_match is Nan when result_type is no result only

df[df['player_of_match'].isna()][['event_name', 'season', 'match_number', 'date', 'city', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'team1_runs',
       'team1_wickets', 'team2_runs', 'team2_wickets', 'winner', 'result_type',
       'win_by_runs', 'win_by_wickets', 'player_of_match']]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,player_of_match
241,Indian Premier League,2011,68.0,2011-05-21,Delhi,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,56,3,0,0,No Result,no result,0,0,NaN
485,Indian Premier League,2015,29.0,2015-04-29,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,200,7,0,0,No Result,no result,0,0,NaN
511,Indian Premier League,2015,55.0,2015-05-17,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,2,0,187,5,No Result,no result,0,0,NaN
744,Indian Premier League,2019,49.0,2019-04-30,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,62,7,41,1,No Result,no result,0,0,NaN
994,Indian Premier League,2023,45.0,2023-05-03,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,125,7,0,0,No Result,no result,0,0,NaN
1138,Indian Premier League,2025,44.0,2025-04-26,Kolkata,"Eden Gardens, Kolkata",Punjab Kings,Kolkata Knight Riders,Punjab Kings,bat,201,4,7,0,No Result,no result,0,0,NaN
1149,Indian Premier League,2025,55.0,2025-05-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Delhi Capitals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,133,7,0,0,No Result,no result,0,0,NaN
1152,Indian Premier League,2025,58.0,2025-05-08,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Punjab Kings,Delhi Capitals,Punjab Kings,bat,122,1,0,0,No Result,no result,0,0,NaN
1180,Indian Premier League,2026,12.0,2026-04-06,Kolkata,"Eden Gardens, Kolkata",Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,bat,25,2,0,0,No Result,no result,0,0,NaN

In [18]:
df['player_of_match'] = df['player_of_match'].fillna('N/A')

In [19]:
print(df['player_of_match'].isna().sum())

0

In [20]:
df.isna().sum()

event_name         0
season             0
match_number       0
date               0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             0
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    0
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
match_type         0
overs_limit        0
balls_per_over     0
gender             0
team_type          0
team1_players      0
team2_players      0
dtype: int64

### Column Standardization

In [21]:
df[['team1', 'team2', 'winner', 'toss_winner','city','venue']].nunique()

team1          19
team2          19
winner         21
toss_winner    19
city           38
venue          60
dtype: int64

In [22]:
df['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Eden Gardens', 'Wankhede Stadium', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Brabourne Stadium, Mumbai',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Arun Jaitley Stadium', 'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'M Chinnaswamy Stadium, Bengaluru',
       'Barsapara Cricket Stadium, Guwahati',
       'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',
       'Shaheed Veer Narayan Singh International Stadium, Raipur'],
      dtype=object)

In [23]:
def standardize_venue(venue_name):
    if pd.isna(venue_name): 
        return venue_name
    
    if 'Feroz Shah Kotla' in venue_name or 'Arun Jaitley' in venue_name: 
        return 'Arun Jaitley Stadium'
    if 'Narendra Modi' in venue_name or 'Sardar Patel' in venue_name: 
        return 'Narendra Modi Stadium'
    
    if 'M.Chinnaswamy' in venue_name or 'M Chinnaswamy' in venue_name: 
        return 'M Chinnaswamy Stadium'
    if 'MA Chidambaram' in venue_name: 
        return 'MA Chidambaram Stadium'
    if 'Punjab Cricket Association' in venue_name: 
        return 'Punjab Cricket Association Stadium'
    if 'Rajiv Gandhi' in venue_name: 
        return 'Rajiv Gandhi International Stadium'
    return venue_name.split(',')[0].strip()

df['venue'] = df['venue'].apply(standardize_venue)

In [24]:
all_teams = pd.concat([df['team1'], df['team2']]).dropna().unique()

print("Unique Teams:")
print(sorted(all_teams)) # Here Delhi Capitals and Delhi Daredevils is same team but with different name and so other teams too

print("\n\nUnique Cities:")
print(sorted(df['city'].dropna().unique())) # same here banglore and bengluru is the same city but with different names

Unique Teams:
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Delhi Daredevils', 'Gujarat Lions', 'Gujarat Titans', 'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Rising Pune Supergiants', 'Royal Challengers Bangalore', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']


Unique Cities:
['Abu Dhabi', 'Ahmedabad', 'Bangalore', 'Bengaluru', 'Bloemfontein', 'Cape Town', 'Centurion', 'Chandigarh', 'Chennai', 'Cuttack', 'Delhi', 'Dharamsala', 'Dubai', 'Durban', 'East London', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Johannesburg', 'Kanpur', 'Kimberley', 'Kochi', 'Kolkata', 'Lucknow', 'Mohali', 'Mumbai', 'Nagpur', 'Navi Mumbai', 'New Chandigarh', 'Port Elizabeth', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Sharjah', 'Unknown', 'Visakhapatnam']

In [25]:
team_name_mapping = {
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
}

columns_to_update = ['team1', 'team2', 'winner', 'toss_winner']
for col in columns_to_update:
    df[col] = df[col].replace(team_name_mapping)

In [26]:
df['city'] = df['city'].replace({'Bangalore': 'Bengaluru'})

In [27]:
df[['team1', 'team2', 'winner', 'toss_winner','city','venue']].nunique()

team1          15
team2          15
winner         17
toss_winner    15
city           37
venue          38
dtype: int64

### DF To CSV

In [28]:
df.to_csv('final_dataset.csv')